pipeline:
  name: pip1
  identifier: pip1
  projectIdentifier: vivekproj
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
