pipeline:
  name: testtstsdc
  identifier: testtstsdc
  projectIdentifier: s
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: zq
        identifier: zq
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
